package com.springJpa.springJpa.enums;

public enum Designation {
QA,SENIOR_QA,SE,SSE,ARCHITECT,SENIOR_ARCHITECT,ASSOCATATE_MARKTER,MARKETING_MANAGER,ASSOCIATE_BUSINESS_DEVELOPER,SENIOR_BUSINESS_DEVELOPER,HR
}
